env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-duplicate-imports:
    - error
    - { "includeExports": true }
  camelcase:
    - error
    - {}
  curly:
    - error
  eqeqeq:
    - error
    - always
  prefer-const:
    - error
  require-await:
    - error
  no-duplicate-case:
    - error
  no-dupe-keys:
    - error
  no-dupe-else-if:
    - error
  no-undef:
    - 0